In [1]:
# Install R base and rpy2 for running R within Colab
!apt-get -y install r-base > /dev/null
!pip -q install rpy2

In [2]:
# Clone the repository containing all datasets
!git clone https://github.com/Amaan449/DBA_ASSIGNMENT.git
%cd DBA_ASSIGNMENT

Cloning into 'DBA_ASSIGNMENT'...
remote: Enumerating objects: 67, done.
remote: Counting objects: 100% (67/67), done.
remote: Compressing objects: 100% (52/52), done.
remote: Total 67 (delta 7), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (67/67), 221.15 KiB | 3.40 MiB/s, done.
Resolving deltas: 100% (7/7), done.
/content/DBA_ASSIGNMENT

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

# Load all CSV files
customers   = pd.read_csv('Datasets/customers.csv')
orders      = pd.read_csv('Datasets/orders.csv')
deliveries  = pd.read_csv('Datasets/deliveries.csv')
drivers     = pd.read_csv('Datasets/drivers.csv')
vehicles    = pd.read_csv('Datasets/vehicles.csv')
hubs        = pd.read_csv('Datasets/hubs.csv')
incidents   = pd.read_csv('Datasets/incidents.csv')
complaints  = pd.read_csv('Datasets/complaints.csv')
app_events  = pd.read_csv('Datasets/app_events.csv')

# Show the first few rows and basic information for all loaded datasets
print(customers.head())
print(customers.info())
print(orders.head())
print(orders.info())
print(deliveries.head())
print(deliveries.info())
print(drivers.head())
print(drivers.info())
print(vehicles.head())
print(vehicles.info())
print(hubs.head())
print(hubs.info())
print(incidents.head())
print(incidents.info())
print(complaints.head())
print(complaints.info())
print(app_events.head())
print(app_events.info())

  customer_id  age  home_zone customer_type          signup_date  \
0       C0001   26      North           SME  2024-11-27 04:25:00
1       C0002   61    AIRPORT      Consumer  2025-10-28 01:04:00
2       C0003   66       East      Consumer  2025-07-02 03:23:00
3       C0004   75    CENTRAL      Consumer  2025-08-19 01:58:00
4       C0005   26  Riverside      Consumer  2025-06-03 06:02:00

   loyalty_score  app_engagement_score preferred_channel account_status
0           44.9                  69.2               App         Active
1           55.4                  66.6               App         Active
2           75.9                  33.8               NaN         Active
3           32.5                  33.0               App         Active
4           55.9                 100.0               Web         Active
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 650 entries, 0 to 649
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           650 non-null    object
 1   age                   650 non-null    int64
 2   home_zone             650 non-null    object
 3   customer_type         650 non-null    object
 4   signup_date           650 non-null    object
 5   loyalty_score         630 non-null    float64
 6   app_engagement_score  650 non-null    float64
 7   preferred_channel     637 non-null    object
 8   account_status        650 non-null    object
dtypes: float64(2), int64(1), object(6)
memory usage: 45.8+ KB
None
  order_id customer_id service_type     order_created_at  \
0   O00001       C0292    Passenger  2024-08-20 14:43:00
1   O00002       C0459    Passenger  2024-05-14 22:16:00
2   O00003       C0161    Passenger  2025-09-02 14:37:00
3   O00004       C0520       Parcel  2025-01-11 17:15:00
4   O00005       C0558       Retail  2025-02-17 19:32:00

   promised_window_hours pickup_zone dropoff_zone priority_level  order_value  \
0                      6     Airport        South         Medium       126.65
1                     24       North      AIRPORT            Low       109.30
2                      4        West      AIRPORT           High        33.50
3                      2   RiverSide        North         Medium        10.04
4                     12   Riverside        SOUTH            Low       125.58

  booking_channel  special_handling_flag
0             App                      0
1             App                      0
2           Phone                      0
3             App                      1
4           Phone                      0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1250 entries, 0 to 1249
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               1250 non-null   object
 1   customer_id            1250 non-null   object
 2   service_type           1250 non-null   object
 3   order_created_at       1250 non-null   object
 4   promised_window_hours  1250 non-null   int64
 5   pickup_zone            1250 non-null   object
 6   dropoff_zone           1250 non-null   object
 7   priority_level         1250 non-null   object
 8   order_value            1250 non-null   float64
 9   booking_channel        1225 non-null   object
 10  special_handling_flag  1250 non-null   int64
dtypes: float64(1), int64(2), object(8)
memory usage: 107.6+ KB
None
  delivery_id order_id driver_id vehicle_id hub_id        dispatch_time  \
0     DL00001   O00938      D004       V056    H05  2024-06-18 10:57:00
1     DL00002   O00004      D138       V007    H02  2025-01-11 18:45:00
2     DL00003   O00639      D006       V049    H02  2025-06-02 20:39:00
3     DL00004   O00313      D116       V055    H02  2024-03-08 23:31:00
4     DL00005   O00844      D108       V034    H01  2025-09-21 11:43:00

        delivery_completed_at delivery_status  route_distance_km  \
0  2024-06-19 09:05:59.904311          Failed              17.26
1  2025-01-11 17:39:00.000000          OnTime              10.34
2  2025-06-02 21:45:32.366770          OnTime               7.92
3  2024-03-09 23:30:08.103702         Delayed              16.42
4  2025-09-21 15:45:34.131056          OnTime              14.52

   manual_route_override_count  proof_of_completion_missing  \
0                            1                            0
1                            1                            0
2                            0                            0
3                            0                            0
4                            1                            0

   customer_rating_post_delivery  fuel_or_charge_cost
0                           3.07                12.05
1                           5.00                13.41
2                           4.98                 8.51
3                           4.18                13.62
4                           4.18                 9.22
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   delivery_id                    950 non-null    object
 1   order_id                       950 non-null    object
 2   driver_id                      950 non-null    object
 3   vehicle_id                     950 non-null    object
 4   hub_id                         950 non-null    object
 5   dispatch_time                  950 non-null    object
 6   delivery_completed_at          931 non-null    object
 7   delivery_status                950 non-null    object
 8   route_distance_km              950 non-null    float64
 9   manual_route_override_count    950 non-null    int64
 10  proof_of_completion_missing    950 non-null    int64
 11  customer_rating_post_delivery  936 non-null    float64
 12  fuel_or_charge_cost            950 non-null    float64
dtypes: float64(3), int64(2), object(8)
memory usage: 96.6+ KB
None
  driver_id base_zone employment_type  years_experience  training_score  \
0      D001   AIRPORT        FullTime                 8            67.8
1      D002   Central        FullTime                 4            42.4
2      D003   AIRPORT        FullTime                11            96.5
3      D004   Airport        PartTime                13            88.9
4      D005     north        FullTime                 3            69.7

   driver_rating shift_preference  active_flag
0           3.54          Morning            1
1           3.94          Evening            1
2           5.00          Evening            1
3           4.75          Morning            1
4           4.14          Morning            1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170 entries, 0 to 169
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   driver_id         170 non-null    object
 1   base_zone         170 non-null    object
 2   employment_type   170 non-null    object
 3   years_experience  170 non-null    int64
 4   training_score    163 non-null    float64
 5   driver_rating     170 non-null    float64
 6   shift_preference  170 non-null    object
 7   active_flag       170 non-null    int64
dtypes: float64(2), int64(2), object(4)
memory usage: 10.8+ KB
None
  vehicle_id vehicle_type assigned_zone      commission_date  \
0       V001           EV         North  2024-12-28 23:48:00
1       V002           EV       AIRPORT  2024-04-21 16:14:00
2       V003     CargoVan         north  2025-11-24 23:59:00
3       V004       Hybrid     RiverSide  2024-06-07 13:21:00
4       V005     CargoVan          West  2025-11-15 11:08:00

   battery_health_pct  odometer_km maintenance_status telematics_version
0                71.8        56928             Active               v2.2
1                67.9       159368           InRepair               v2.2
2                91.7       219359             Active               v2.1
3                 NaN        36310             Active               v2.2
4                58.6       146638             Active               v2.2
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   vehicle_id          120 non-null    object
 1   vehicle_type        120 non-null    object
 2   assigned_zone       120 non-null    object
 3   commission_date     120 non-null    object
 4   battery_health_pct  116 non-null    float64
 5   odometer_km         120 non-null    int64
 6   maintenance_status  120 non-null    object
 7   telematics_version  120 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 7.6+ KB
None
  hub_id        hub_name     zone   hub_type  capacity_score
0    H01  North Exchange    North   Dispatch              82
1    H02      South Link    South   Dispatch              78
2    H03       East Dock     East  Warehouse              74
3    H04       West Gate     West   Dispatch              69
4    H05    Central Core  Central    Control              88
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   hub_id          8 non-null      object
 1   hub_name        8 non-null      object
 2   zone            8 non-null      object
 3   hub_type        8 non-null      object
 4   capacity_score  8 non-null      int64
dtypes: int64(1), object(4)
memory usage: 452.0+ bytes
None
  incident_id delivery_id     incident_type          reported_at severity  \
0       I0001     DL00221      BatteryAlert  2024-03-11 23:46:00   Medium
1       I0002     DL00578      BatteryAlert  2024-02-21 10:56:00      Low
2       I0003     DL00175  TemperatureIssue  2025-04-17 23:22:00   Medium
3       I0004     DL00417      ProofMissing  2025-02-09 00:16:00   Medium
4       I0005     DL00897    RouteDeviation  2025-01-04 02:49:00      Low

  resolution_status  resolved_hours
0         Escalated            12.3
1              Open             9.6
2              Open            22.0
3            Closed             9.8
4              Open            13.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   incident_id        280 non-null    object
 1   delivery_id        280 non-null    object
 2   incident_type      280 non-null    object
 3   reported_at        280 non-null    object
 4   severity           280 non-null    object
 5   resolution_status  280 non-null    object
 6   resolved_hours     263 non-null    float64
dtypes: float64(1), object(6)
memory usage: 15.4+ KB
None
  complaint_id customer_id order_id complaint_type  channel severity  \
0       CP0001       C0464   O00814       AppIssue      App     High
1       CP0002       C0056   O00628   MissedPickup    Phone   Medium
2       CP0003       C0469   O00384          Delay  Chatbot     High
3       CP0004       C0631   O00406          Delay      App   Medium
4       CP0005       C0535   O00154          Delay    Email   Medium

            created_at            status  resolution_days  compensation_amount
0  2025-03-30 02:36:00              Open               11                23.99
1  2024-11-07 10:05:00              Open                4                21.64
2  2024-01-02 15:47:00              Open               16                26.41
3  2025-01-14 13:07:00  AwaitingCustomer                7                23.44
4  2024-08-31 05:56:00          Resolved                1                16.18
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   complaint_id         320 non-null    object
 1   customer_id          320 non-null    object
 2   order_id             320 non-null    object
 3   complaint_type       320 non-null    object
 4   channel              320 non-null    object
 5   severity             320 non-null    object
 6   created_at           320 non-null    object
 7   status               320 non-null    object
 8   resolution_days      320 non-null    int64
 9   compensation_amount  304 non-null    float64
dtypes: float64(1), int64(1), object(8)
memory usage: 25.1+ KB
None
  event_id customer_id order_id      event_timestamp    event_type session_id  \
0  AE00001       C0488      NaN  2024-08-09 03:25:00   eta_refresh     S19847
1  AE00002       C0595   O00950  2024-02-13 22:29:00  search_route     S32766
2  AE00003       C0494   O00170  2025-08-11 09:29:00   chat_opened     S99516
3  AE00004       C0407   O00756  2025-08-23 17:38:00   eta_refresh     S41236
4  AE00005       C0506      NaN  2024-05-29 10:33:00  search_route     S12030

  device_type zone_context  api_latency_ms  success_flag
0     Android        north             301             1
1     Android        SOUTH              60             1
2         iOS      Airport            1118             1
3         iOS      CENTRAL             442             1
4         iOS        north              60             1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 640 entries, 0 to 639
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   event_id         640 non-null    object
 1   customer_id      640 non-null    object
 2   order_id         496 non-null    object
 3   event_timestamp  640 non-null    object
 4   event_type       640 non-null    object
 5   session_id       640 non-null    object
 6   device_type      640 non-null    object
 7   zone_context     640 non-null    object
 8   api_latency_ms   640 non-null    int64
 9   success_flag     640 non-null    int64
dtypes: int64(2), object(8)
memory usage: 50.1+ KB
None

In [4]:
# Store in dictionary for easy access
datasets = {
    "customers": customers,
    "orders": orders,
    "deliveries": deliveries,
    "drivers": drivers,
    "vehicles": vehicles,
    "hubs": hubs,
    "incidents": incidents,
    "complaints": complaints,
    "app_events": app_events
}

# Display shape of each dataset
for name, df in datasets.items():
    print(f"{name}: {df.shape}")

customers: (650, 9)
orders: (1250, 11)
deliveries: (950, 13)
drivers: (170, 8)
vehicles: (120, 8)
hubs: (8, 5)
incidents: (280, 7)
complaints: (320, 10)
app_events: (640, 10)

In [5]:
# Print a header for each dataset and display its first few rows
for name, df in datasets.items():
    print("\n---", name.upper(), "---")
    display(df.head())

--- CUSTOMERS ---

,customer_id,age,home_zone,customer_type,signup_date,loyalty_score,app_engagement_score,preferred_channel,account_status
0,C0001,26,North,SME,2024-11-27 04:25:00,44.9,69.2,App,Active
1,C0002,61,AIRPORT,Consumer,2025-10-28 01:04:00,55.4,66.6,App,Active
2,C0003,66,East,Consumer,2025-07-02 03:23:00,75.9,33.8,NaN,Active
3,C0004,75,CENTRAL,Consumer,2025-08-19 01:58:00,32.5,33.0,App,Active
4,C0005,26,Riverside,Consumer,2025-06-03 06:02:00,55.9,100.0,Web,Active

--- ORDERS ---

,order_id,customer_id,service_type,order_created_at,promised_window_hours,pickup_zone,dropoff_zone,priority_level,order_value,booking_channel,special_handling_flag
0,O00001,C0292,Passenger,2024-08-20 14:43:00,6,Airport,South,Medium,126.65,App,0
1,O00002,C0459,Passenger,2024-05-14 22:16:00,24,North,AIRPORT,Low,109.30,App,0
2,O00003,C0161,Passenger,2025-09-02 14:37:00,4,West,AIRPORT,High,33.50,Phone,0
3,O00004,C0520,Parcel,2025-01-11 17:15:00,2,RiverSide,North,Medium,10.04,App,1
4,O00005,C0558,Retail,2025-02-17 19:32:00,12,Riverside,SOUTH,Low,125.58,Phone,0

--- DELIVERIES ---

,delivery_id,order_id,driver_id,vehicle_id,hub_id,dispatch_time,delivery_completed_at,delivery_status,route_distance_km,manual_route_override_count,proof_of_completion_missing,customer_rating_post_delivery,fuel_or_charge_cost
0,DL00001,O00938,D004,V056,H05,2024-06-18 10:57:00,2024-06-19 09:05:59.904311,Failed,17.26,1,0,3.07,12.05
1,DL00002,O00004,D138,V007,H02,2025-01-11 18:45:00,2025-01-11 17:39:00.000000,OnTime,10.34,1,0,5.00,13.41
2,DL00003,O00639,D006,V049,H02,2025-06-02 20:39:00,2025-06-02 21:45:32.366770,OnTime,7.92,0,0,4.98,8.51
3,DL00004,O00313,D116,V055,H02,2024-03-08 23:31:00,2024-03-09 23:30:08.103702,Delayed,16.42,0,0,4.18,13.62
4,DL00005,O00844,D108,V034,H01,2025-09-21 11:43:00,2025-09-21 15:45:34.131056,OnTime,14.52,1,0,4.18,9.22

--- DRIVERS ---

,driver_id,base_zone,employment_type,years_experience,training_score,driver_rating,shift_preference,active_flag
0,D001,AIRPORT,FullTime,8,67.8,3.54,Morning,1
1,D002,Central,FullTime,4,42.4,3.94,Evening,1
2,D003,AIRPORT,FullTime,11,96.5,5.00,Evening,1
3,D004,Airport,PartTime,13,88.9,4.75,Morning,1
4,D005,north,FullTime,3,69.7,4.14,Morning,1

--- VEHICLES ---

,vehicle_id,vehicle_type,assigned_zone,commission_date,battery_health_pct,odometer_km,maintenance_status,telematics_version
0,V001,EV,North,2024-12-28 23:48:00,71.8,56928,Active,v2.2
1,V002,EV,AIRPORT,2024-04-21 16:14:00,67.9,159368,InRepair,v2.2
2,V003,CargoVan,north,2025-11-24 23:59:00,91.7,219359,Active,v2.1
3,V004,Hybrid,RiverSide,2024-06-07 13:21:00,NaN,36310,Active,v2.2
4,V005,CargoVan,West,2025-11-15 11:08:00,58.6,146638,Active,v2.2

--- HUBS ---

  hub_id        hub_name     zone   hub_type  capacity_score
0    H01  North Exchange    North   Dispatch              82
1    H02      South Link    South   Dispatch              78
2    H03       East Dock     East  Warehouse              74
3    H04       West Gate     West   Dispatch              69
4    H05    Central Core  Central    Control              88

--- INCIDENTS ---

,incident_id,delivery_id,incident_type,reported_at,severity,resolution_status,resolved_hours
0,I0001,DL00221,BatteryAlert,2024-03-11 23:46:00,Medium,Escalated,12.3
1,I0002,DL00578,BatteryAlert,2024-02-21 10:56:00,Low,Open,9.6
2,I0003,DL00175,TemperatureIssue,2025-04-17 23:22:00,Medium,Open,22.0
3,I0004,DL00417,ProofMissing,2025-02-09 00:16:00,Medium,Closed,9.8
4,I0005,DL00897,RouteDeviation,2025-01-04 02:49:00,Low,Open,13.0

--- COMPLAINTS ---

,complaint_id,customer_id,order_id,complaint_type,channel,severity,created_at,status,resolution_days,compensation_amount
0,CP0001,C0464,O00814,AppIssue,App,High,2025-03-30 02:36:00,Open,11,23.99
1,CP0002,C0056,O00628,MissedPickup,Phone,Medium,2024-11-07 10:05:00,Open,4,21.64
2,CP0003,C0469,O00384,Delay,Chatbot,High,2024-01-02 15:47:00,Open,16,26.41
3,CP0004,C0631,O00406,Delay,App,Medium,2025-01-14 13:07:00,AwaitingCustomer,7,23.44
4,CP0005,C0535,O00154,Delay,Email,Medium,2024-08-31 05:56:00,Resolved,1,16.18

--- APP_EVENTS ---

,event_id,customer_id,order_id,event_timestamp,event_type,session_id,device_type,zone_context,api_latency_ms,success_flag
0,AE00001,C0488,NaN,2024-08-09 03:25:00,eta_refresh,S19847,Android,north,301,1
1,AE00002,C0595,O00950,2024-02-13 22:29:00,search_route,S32766,Android,SOUTH,60,1
2,AE00003,C0494,O00170,2025-08-11 09:29:00,chat_opened,S99516,iOS,Airport,1118,1
3,AE00004,C0407,O00756,2025-08-23 17:38:00,eta_refresh,S41236,iOS,CENTRAL,442,1
4,AE00005,C0506,NaN,2024-05-29 10:33:00,search_route,S12030,iOS,north,60,1

In [6]:
# Print a header for each dataset, then show its info and count of missing values
for name, df in datasets.items():
    print("\n---", name.upper(), "---")
    print(df.info())
    print(df.isna().sum())

--- CUSTOMERS ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 650 entries, 0 to 649
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           650 non-null    object
 1   age                   650 non-null    int64
 2   home_zone             650 non-null    object
 3   customer_type         650 non-null    object
 4   signup_date           650 non-null    object
 5   loyalty_score         630 non-null    float64
 6   app_engagement_score  650 non-null    float64
 7   preferred_channel     637 non-null    object
 8   account_status        650 non-null    object
dtypes: float64(2), int64(1), object(6)
memory usage: 45.8+ KB
None
customer_id              0
age                      0
home_zone                0
customer_type            0
signup_date              0
loyalty_score           20
app_engagement_score     0
preferred_channel       13
account_status           0
dtype: int64

--- ORDERS ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1250 entries, 0 to 1249
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               1250 non-null   object
 1   customer_id            1250 non-null   object
 2   service_type           1250 non-null   object
 3   order_created_at       1250 non-null   object
 4   promised_window_hours  1250 non-null   int64
 5   pickup_zone            1250 non-null   object
 6   dropoff_zone           1250 non-null   object
 7   priority_level         1250 non-null   object
 8   order_value            1250 non-null   float64
 9   booking_channel        1225 non-null   object
 10  special_handling_flag  1250 non-null   int64
dtypes: float64(1), int64(2), object(8)
memory usage: 107.6+ KB
None
order_id                  0
customer_id               0
service_type              0
order_created_at          0
promised_window_hours     0
pickup_zone               0
dropoff_zone              0
priority_level            0
order_value               0
booking_channel          25
special_handling_flag     0
dtype: int64

--- DELIVERIES ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   delivery_id                    950 non-null    object
 1   order_id                       950 non-null    object
 2   driver_id                      950 non-null    object
 3   vehicle_id                     950 non-null    object
 4   hub_id                         950 non-null    object
 5   dispatch_time                  950 non-null    object
 6   delivery_completed_at          931 non-null    object
 7   delivery_status                950 non-null    object
 8   route_distance_km              950 non-null    float64
 9   manual_route_override_count    950 non-null    int64
 10  proof_of_completion_missing    950 non-null    int64
 11  customer_rating_post_delivery  936 non-null    float64
 12  fuel_or_charge_cost            950 non-null    float64
dtypes: float64(3), int64(2), object(8)
memory usage: 96.6+ KB
None
delivery_id                       0
order_id                          0
driver_id                         0
vehicle_id                        0
hub_id                            0
dispatch_time                     0
delivery_completed_at            19
delivery_status                   0
route_distance_km                 0
manual_route_override_count       0
proof_of_completion_missing       0
customer_rating_post_delivery    14
fuel_or_charge_cost               0
dtype: int64

--- DRIVERS ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170 entries, 0 to 169
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   driver_id         170 non-null    object
 1   base_zone         170 non-null    object
 2   employment_type   170 non-null    object
 3   years_experience  170 non-null    int64
 4   training_score    163 non-null    float64
 5   driver_rating     170 non-null    float64
 6   shift_preference  170 non-null    object
 7   active_flag       170 non-null    int64
dtypes: float64(2), int64(2), object(4)
memory usage: 10.8+ KB
None
driver_id           0
base_zone           0
employment_type     0
years_experience    0
training_score      7
driver_rating       0
shift_preference    0
active_flag         0
dtype: int64

--- VEHICLES ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   vehicle_id          120 non-null    object
 1   vehicle_type        120 non-null    object
 2   assigned_zone       120 non-null    object
 3   commission_date     120 non-null    object
 4   battery_health_pct  116 non-null    float64
 5   odometer_km         120 non-null    int64
 6   maintenance_status  120 non-null    object
 7   telematics_version  120 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 7.6+ KB
None
vehicle_id            0
vehicle_type          0
assigned_zone         0
commission_date       0
battery_health_pct    4
odometer_km           0
maintenance_status    0
telematics_version    0
dtype: int64

--- HUBS ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   hub_id          8 non-null      object
 1   hub_name        8 non-null      object
 2   zone            8 non-null      object
 3   hub_type        8 non-null      object
 4   capacity_score  8 non-null      int64
dtypes: int64(1), object(4)
memory usage: 452.0+ bytes
None
hub_id            0
hub_name          0
zone              0
hub_type          0
capacity_score    0
dtype: int64

--- INCIDENTS ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   incident_id        280 non-null    object
 1   delivery_id        280 non-null    object
 2   incident_type      280 non-null    object
 3   reported_at        280 non-null    object
 4   severity           280 non-null    object
 5   resolution_status  280 non-null    object
 6   resolved_hours     263 non-null    float64
dtypes: float64(1), object(6)
memory usage: 15.4+ KB
None
incident_id           0
delivery_id           0
incident_type         0
reported_at           0
severity              0
resolution_status     0
resolved_hours       17
dtype: int64

--- COMPLAINTS ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   complaint_id         320 non-null    object
 1   customer_id          320 non-null    object
 2   order_id             320 non-null    object
 3   complaint_type       320 non-null    object
 4   channel              320 non-null    object
 5   severity             320 non-null    object
 6   created_at           320 non-null    object
 7   status               320 non-null    object
 8   resolution_days      320 non-null    int64
 9   compensation_amount  304 non-null    float64
dtypes: float64(1), int64(1), object(8)
memory usage: 25.1+ KB
None
complaint_id            0
customer_id             0
order_id                0
complaint_type          0
channel                 0
severity                0
created_at              0
status                  0
resolution_days         0
compensation_amount    16
dtype: int64

--- APP_EVENTS ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 640 entries, 0 to 639
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   event_id         640 non-null    object
 1   customer_id      640 non-null    object
 2   order_id         496 non-null    object
 3   event_timestamp  640 non-null    object
 4   event_type       640 non-null    object
 5   session_id       640 non-null    object
 6   device_type      640 non-null    object
 7   zone_context     640 non-null    object
 8   api_latency_ms   640 non-null    int64
 9   success_flag     640 non-null    int64
dtypes: int64(2), object(8)
memory usage: 50.1+ KB
None
event_id             0
customer_id          0
order_id           144
event_timestamp      0
event_type           0
session_id           0
device_type          0
zone_context         0
api_latency_ms       0
success_flag         0
dtype: int64

In [7]:
# Standardize all column names to lowercase and remove extra whitespace
for name in datasets:
    datasets[name].columns = datasets[name].columns.str.strip().str.lower()# Standardize all column names to lowercase and remove extra whitespace
for name in datasets:
    datasets[name].columns = datasets[name].columns.str.strip().str.lower()

    # For each specified zone column, print its unique non‑missing values across all datasets that contain it
for col in ["home_zone", "pickup_zone", "dropoff_zone", "base_zone", "zone", "zone_context"]:
    print(f"\n--- {col} ---")
    for name, df in datasets.items():
        if col in df.columns:
            print(name, df[col].dropna().unique())

--- home_zone ---
customers ['North' 'AIRPORT' 'East' 'CENTRAL' 'Riverside' 'WEST' 'north' 'South'
 'West' 'Ctr' 'Airport' 'EAST' 'SOUTH' 'RiverSide' 'NORTH' 'Central']

--- pickup_zone ---
orders ['Airport' 'North' 'West' 'RiverSide' 'Riverside' 'CENTRAL' 'NORTH'
 'South' 'WEST' 'East' 'Ctr' 'SOUTH' 'Central' 'AIRPORT' 'north' 'EAST']

--- dropoff_zone ---
orders ['South' 'AIRPORT' 'North' 'SOUTH' 'East' 'Airport' 'Riverside' 'north'
 'Central' 'Ctr' 'CENTRAL' 'NORTH' 'RiverSide' 'West' 'EAST' 'WEST']

--- base_zone ---
drivers ['AIRPORT' 'Central' 'Airport' 'north' 'CENTRAL' 'North' 'SOUTH' 'West'
 'East' 'NORTH' 'EAST' 'WEST' 'Riverside' 'South' 'RiverSide' 'Ctr']

--- zone ---
hubs ['North' 'South' 'East' 'West' 'Central' 'Airport' 'Riverside']

--- zone_context ---
app_events ['north' 'SOUTH' 'Airport' 'CENTRAL' 'West' 'South' 'Ctr' 'North' 'WEST'
 'AIRPORT' 'RiverSide' 'NORTH' 'EAST' 'Riverside' 'East' 'Central']

In [8]:
# Define a mapping from common zone spellings to standardized zone names
zone_map = {
    "north": "North",
    "south": "South",
    "east": "East",
    "west": "West",
    "central": "Central",
    "ctr": "Central",
    "riverside": "Riverside",
    "airpor": "Airport",
    "airport": "Airport"
}

# Function to clean and standardize zone values using the zone_map
def clean_zone(x):
    if pd.isna(x):
        return np.nan
    x = str(x).strip()
    key = x.lower()
    return zone_map.get(key, x.title())
# Apply the clean_zone function to standardize zone values in relevant columns
if "home_zone" in customers.columns:
    customers["home_zone"] = customers["home_zone"].apply(clean_zone)

if "pickup_zone" in orders.columns:
    orders["pickup_zone"] = orders["pickup_zone"].apply(clean_zone)

if "dropoff_zone" in orders.columns:
    orders["dropoff_zone"] = orders["dropoff_zone"].apply(clean_zone)

if "base_zone" in drivers.columns:
    drivers["base_zone"] = drivers["base_zone"].apply(clean_zone)

if "zone" in hubs.columns:
    hubs["zone"] = hubs["zone"].apply(clean_zone)

if "zone_context" in app_events.columns:
    app_events["zone_context"] = app_events["zone_context"].apply(clean_zone)


# Show unique non‑missing values for each zone column after cleaning
for col in ["home_zone", "pickup_zone", "dropoff_zone", "base_zone", "zone", "zone_context"]:
    print(f"\n--- {col} AFTER CLEANING ---")
    for name, df in {
        "customers": customers,
        "orders": orders,
        "drivers": drivers,
        "hubs": hubs,
        "app_events": app_events
    }.items():
        if col in df.columns:
            print(name, df[col].dropna().unique())

--- home_zone AFTER CLEANING ---
customers ['North' 'Airport' 'East' 'Central' 'Riverside' 'West' 'South']

--- pickup_zone AFTER CLEANING ---
orders ['Airport' 'North' 'West' 'Riverside' 'Central' 'South' 'East']

--- dropoff_zone AFTER CLEANING ---
orders ['South' 'Airport' 'North' 'East' 'Riverside' 'Central' 'West']

--- base_zone AFTER CLEANING ---
drivers ['Airport' 'Central' 'North' 'South' 'West' 'East' 'Riverside']

--- zone AFTER CLEANING ---
hubs ['North' 'South' 'East' 'West' 'Central' 'Airport' 'Riverside']

--- zone_context AFTER CLEANING ---
app_events ['North' 'South' 'Airport' 'Central' 'West' 'Riverside' 'East']

In [9]:
# Convert datetime columns
date_cols = {
    "customers": ["signup_date"],
    "orders": ["order_created_at"],
    "deliveries": ["dispatch_time", "delivery_completed_at"],
    "complaints": ["created_at"],
    "incidents": ["reported_at"],
    "app_events": ["event_timestamp"]
}

dfs = {
    "customers": customers,
    "orders": orders,
    "deliveries": deliveries,
    "complaints": complaints,
    "incidents": incidents,
    "app_events": app_events
}

for name, cols in date_cols.items():
    df = dfs[name]
    for col in cols:
        if col in df.columns:
            df[col] = pd.to_datetime(df[col], errors="coerce")

# Convert numeric columns
numeric_conversions = {
    "customers": ["loyalty_score", "app_engagement_score"],
    "orders": ["promised_window_hours", "order_value", "special_handling_flag"],
    "deliveries": ["route_distance_km", "manual_route_override_count",
                   "proof_of_completion_missing", "customer_rating_post_delivery",
                   "fuel_or_charge_cost"],
    "drivers": ["years_experience", "training_score", "driver_rating", "active_flag"],
    "vehicles": ["battery_health_pct", "maintenance_status"],
    "complaints": ["compensation_amount"],
    "incidents": ["resolved_hours"],
    "app_events": ["api_latency_ms", "success_flag"]
}

dfs_num = {
    "customers": customers,
    "orders": orders,
    "deliveries": deliveries,
    "drivers": drivers,
    "vehicles": vehicles,
    "complaints": complaints,
    "incidents": incidents,
    "app_events": app_events
}

for name, cols in numeric_conversions.items():
    df = dfs_num[name]
    for col in cols:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

print("Data type conversion finished.")

Data type conversion finished.

In [10]:
# Show the count of missing values for each dataset, only for columns that have at least one NaN (Not a Number)
for name, df in datasets.items():
    print(f"\n--- {name.upper()} MISSING VALUES ---")
    print(df.isna().sum()[df.isna().sum() > 0])

--- CUSTOMERS MISSING VALUES ---
loyalty_score        20
preferred_channel    13
dtype: int64

--- ORDERS MISSING VALUES ---
booking_channel    25
dtype: int64

--- DELIVERIES MISSING VALUES ---
delivery_completed_at            19
customer_rating_post_delivery    14
dtype: int64

--- DRIVERS MISSING VALUES ---
training_score    7
dtype: int64

--- VEHICLES MISSING VALUES ---
battery_health_pct      4
maintenance_status    120
dtype: int64

--- HUBS MISSING VALUES ---
Series([], dtype: int64)

--- INCIDENTS MISSING VALUES ---
resolved_hours    17
dtype: int64

--- COMPLAINTS MISSING VALUES ---
compensation_amount    16
dtype: int64

--- APP_EVENTS MISSING VALUES ---
order_id    144
dtype: int64

In [11]:
# Quick missing values summary
for name, df in datasets.items():
    miss = df.isna().sum()
    miss = miss[miss > 0]
    if len(miss) > 0:
        print(f"\n{name} missing values:\n{miss}")

# Remove duplicate rows
for name, df in datasets.items():
    before = df.shape[0]
    datasets[name] = df.drop_duplicates()
    after = datasets[name].shape[0]
    print(f"{name}: removed {before - after} duplicates")

customers missing values:
loyalty_score        20
preferred_channel    13
dtype: int64

orders missing values:
booking_channel    25
dtype: int64

deliveries missing values:
delivery_completed_at            19
customer_rating_post_delivery    14
dtype: int64

drivers missing values:
training_score    7
dtype: int64

vehicles missing values:
battery_health_pct      4
maintenance_status    120
dtype: int64

incidents missing values:
resolved_hours    17
dtype: int64

complaints missing values:
compensation_amount    16
dtype: int64

app_events missing values:
order_id    144
dtype: int64
customers: removed 0 duplicates
orders: removed 0 duplicates
deliveries: removed 0 duplicates
drivers: removed 0 duplicates
vehicles: removed 0 duplicates
hubs: removed 0 duplicates
incidents: removed 0 duplicates
complaints: removed 0 duplicates
app_events: removed 0 duplicates

In [12]:
# Print the info summary for each dataset to review dtypes and non‑null counts
for name, df in {
    "customers": customers,
    "orders": orders,
    "deliveries": deliveries,
    "drivers": drivers,
    "vehicles": vehicles,
    "hubs": hubs,
    "incidents": incidents,
    "complaints": complaints,
    "app_events": app_events
}.items():
    print(f"\n--- {name.upper()} ---")
    print(df.info())

--- CUSTOMERS ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 650 entries, 0 to 649
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           650 non-null    object
 1   age                   650 non-null    int64
 2   home_zone             650 non-null    object
 3   customer_type         650 non-null    object
 4   signup_date           650 non-null    datetime64[ns]
 5   loyalty_score         630 non-null    float64
 6   app_engagement_score  650 non-null    float64
 7   preferred_channel     637 non-null    object
 8   account_status        650 non-null    object
dtypes: datetime64[ns](1), float64(2), int64(1), object(5)
memory usage: 45.8+ KB
None

--- ORDERS ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1250 entries, 0 to 1249
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               1250 non-null   object
 1   customer_id            1250 non-null   object
 2   service_type           1250 non-null   object
 3   order_created_at       1250 non-null   datetime64[ns]
 4   promised_window_hours  1250 non-null   int64
 5   pickup_zone            1250 non-null   object
 6   dropoff_zone           1250 non-null   object
 7   priority_level         1250 non-null   object
 8   order_value            1250 non-null   float64
 9   booking_channel        1225 non-null   object
 10  special_handling_flag  1250 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(2), object(7)
memory usage: 107.6+ KB
None

--- DELIVERIES ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   delivery_id                    950 non-null    object
 1   order_id                       950 non-null    object
 2   driver_id                      950 non-null    object
 3   vehicle_id                     950 non-null    object
 4   hub_id                         950 non-null    object
 5   dispatch_time                  950 non-null    datetime64[ns]
 6   delivery_completed_at          931 non-null    datetime64[ns]
 7   delivery_status                950 non-null    object
 8   route_distance_km              950 non-null    float64
 9   manual_route_override_count    950 non-null    int64
 10  proof_of_completion_missing    950 non-null    int64
 11  customer_rating_post_delivery  936 non-null    float64
 12  fuel_or_charge_cost            950 non-null    float64
dtypes: datetime64[ns](2), float64(3), int64(2), object(6)
memory usage: 96.6+ KB
None

--- DRIVERS ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170 entries, 0 to 169
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   driver_id         170 non-null    object
 1   base_zone         170 non-null    object
 2   employment_type   170 non-null    object
 3   years_experience  170 non-null    int64
 4   training_score    163 non-null    float64
 5   driver_rating     170 non-null    float64
 6   shift_preference  170 non-null    object
 7   active_flag       170 non-null    int64
dtypes: float64(2), int64(2), object(4)
memory usage: 10.8+ KB
None

--- VEHICLES ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   vehicle_id          120 non-null    object
 1   vehicle_type        120 non-null    object
 2   assigned_zone       120 non-null    object
 3   commission_date     120 non-null    object
 4   battery_health_pct  116 non-null    float64
 5   odometer_km         120 non-null    int64
 6   maintenance_status  0 non-null      float64
 7   telematics_version  120 non-null    object
dtypes: float64(2), int64(1), object(5)
memory usage: 7.6+ KB
None

--- HUBS ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   hub_id          8 non-null      object
 1   hub_name        8 non-null      object
 2   zone            8 non-null      object
 3   hub_type        8 non-null      object
 4   capacity_score  8 non-null      int64
dtypes: int64(1), object(4)
memory usage: 452.0+ bytes
None

--- INCIDENTS ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   incident_id        280 non-null    object
 1   delivery_id        280 non-null    object
 2   incident_type      280 non-null    object
 3   reported_at        280 non-null    datetime64[ns]
 4   severity           280 non-null    object
 5   resolution_status  280 non-null    object
 6   resolved_hours     263 non-null    float64
dtypes: datetime64[ns](1), float64(1), object(5)
memory usage: 15.4+ KB
None

--- COMPLAINTS ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   complaint_id         320 non-null    object
 1   customer_id          320 non-null    object
 2   order_id             320 non-null    object
 3   complaint_type       320 non-null    object
 4   channel              320 non-null    object
 5   severity             320 non-null    object
 6   created_at           320 non-null    datetime64[ns]
 7   status               320 non-null    object
 8   resolution_days      320 non-null    int64
 9   compensation_amount  304 non-null    float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(7)
memory usage: 25.1+ KB
None

--- APP_EVENTS ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 640 entries, 0 to 639
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   event_id         640 non-null    object
 1   customer_id      640 non-null    object
 2   order_id         496 non-null    object
 3   event_timestamp  640 non-null    datetime64[ns]
 4   event_type       640 non-null    object
 5   session_id       640 non-null    object
 6   device_type      640 non-null    object
 7   zone_context     640 non-null    object
 8   api_latency_ms   640 non-null    int64
 9   success_flag     640 non-null    int64
dtypes: datetime64[ns](1), int64(2), object(7)
memory usage: 50.1+ KB
None

In [13]:
# Merging attach delivery, customer, hub, driver, and vehicle data

# Enrich orders with delivery information by merging on order_id
orders_full = orders.merge(
    deliveries,
    on="order_id",
    how="left",
    suffixes=("_order", "_del")
)

# Enrich the orders–deliveries table with selected customer features by merging on customer_id
orders_full = orders_full.merge(
    customers[[
        "customer_id",
        "age",
        "home_zone",
        "customer_type",
        "loyalty_score",
        "app_engagement_score",
        "preferred_channel",
        "account_status"
    ]],
    on="customer_id",
    how="left"
)

# Add hub details (hub_name, zone, hub_type, capacity_score) to orders_full by merging on hub_id
orders_full = orders_full.merge(
    hubs[["hub_id", "hub_name", "zone", "hub_type", "capacity_score"]],
    on="hub_id",
    how="left"
)

# Enrich orders with driver attributes by merging on driver_id
orders_full = orders_full.merge(
    drivers[[
        "driver_id",
        "base_zone",
        "employment_type",
        "years_experience",
        "training_score",
        "driver_rating",
        "shift_preference",
        "active_flag"
    ]],
    on="driver_id",
    how="left"
)

# Add vehicle details (e.g., vehicle_type, battery_health_pct, maintenance_status) to orders by merging on vehicle_id
orders_full = orders_full.merge(
    vehicles,
    on="vehicle_id",
    how="left"
)

# OUTPUT ONLY AFTER ALL JOINS ARE COMPLETED
print(orders_full.shape)
orders_full.head()

(1250, 48)

,order_id,customer_id,service_type,order_created_at,promised_window_hours,pickup_zone,dropoff_zone,priority_level,order_value,booking_channel,...,driver_rating,shift_preference,active_flag,vehicle_type,assigned_zone,commission_date,battery_health_pct,odometer_km,maintenance_status,telematics_version
0,O00001,C0292,Passenger,2024-08-20 14:43:00,6,Airport,South,Medium,126.65,App,...,4.70,Morning,1.0,Hybrid,WEST,2024-08-16 01:10:00,93.8,98472.0,NaN,v2.0
1,O00002,C0459,Passenger,2024-05-14 22:16:00,24,North,Airport,Low,109.30,App,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,O00003,C0161,Passenger,2025-09-02 14:37:00,4,West,Airport,High,33.50,Phone,...,3.67,Morning,1.0,CargoVan,East,2024-06-23 11:24:00,60.1,31876.0,NaN,v2.0
3,O00004,C0520,Parcel,2025-01-11 17:15:00,2,Riverside,North,Medium,10.04,App,...,4.61,Evening,1.0,Diesel,AIRPORT,2025-09-17 08:52:00,68.6,78468.0,NaN,v2.2
4,O00005,C0558,Retail,2025-02-17 19:32:00,12,Riverside,South,Low,125.58,Phone,...,4.32,Morning,1.0,Hybrid,AIRPORT,2024-05-28 05:33:00,NaN,191353.0,NaN,v2.1

In [14]:

# Aggregate complaint data by order_id to create summary features for each order
complaints_by_order = (
    complaints
    .groupby("order_id")
    .agg(
        complaint_count=("complaint_id", "count"),
        last_complaint_date=("created_at", "max"),
        any_high_severity=("severity", lambda s: (s == "High").any()),
        avg_compensation=("compensation_amount", "mean")
    )
    .reset_index()
)

complaints_by_order["any_high_severity"] = complaints_by_order["any_high_severity"].astype(int)
complaints_by_order.head()


# Attach aggregated complaint features to orders by merging with complaints_by_order on order_id
orders_full = orders_full.merge(
    complaints_by_order,
    on="order_id",
    how="left"
)

# Aggregate app event data by order_id to create summary features for each order
app_events_by_order = (
    app_events.dropna(subset=["order_id"])
    .groupby("order_id")
    .agg(
        app_event_count=("event_id", "count"),
        last_app_event=("event_timestamp", "max"),
        unique_event_types=("event_type", "nunique"),
        avg_api_latency=("api_latency_ms", "mean")
    )
    .reset_index()
)

app_events_by_order["avg_api_latency"] = app_events_by_order["avg_api_latency"].round(1)

# Attach aggregated app event features to orders_full
orders_full = orders_full.merge(
    app_events_by_order,
    on="order_id",
    how="left"
)

# OUTPUT ONLY AFTER ALL JOINS ARE COMPLETED
print(orders_full.shape)
orders_full.head()

(1250, 56)

,order_id,customer_id,service_type,order_created_at,promised_window_hours,pickup_zone,dropoff_zone,priority_level,order_value,booking_channel,...,maintenance_status,telematics_version,complaint_count,last_complaint_date,any_high_severity,avg_compensation,app_event_count,last_app_event,unique_event_types,avg_api_latency
0,O00001,C0292,Passenger,2024-08-20 14:43:00,6,Airport,South,Medium,126.65,App,...,NaN,v2.0,NaN,NaT,NaN,NaN,1.0,2024-08-02 12:35:00,1.0,204.0
1,O00002,C0459,Passenger,2024-05-14 22:16:00,24,North,Airport,Low,109.30,App,...,NaN,NaN,NaN,NaT,NaN,NaN,1.0,2025-06-26 03:34:00,1.0,244.0
2,O00003,C0161,Passenger,2025-09-02 14:37:00,4,West,Airport,High,33.50,Phone,...,NaN,v2.0,1.0,2025-09-07 14:37:00,0.0,8.66,NaN,NaT,NaN,NaN
3,O00004,C0520,Parcel,2025-01-11 17:15:00,2,Riverside,North,Medium,10.04,App,...,NaN,v2.2,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN
4,O00005,C0558,Retail,2025-02-17 19:32:00,12,Riverside,South,Low,125.58,Phone,...,NaN,v2.1,1.0,2025-02-25 19:32:00,0.0,54.41,NaN,NaT,NaN,NaN

In [15]:
# Finalize the orders_full table by deduplicating on order_id and handling missing values for derived features
orders_full = orders_full.drop_duplicates(subset=["order_id"], keep="first")

orders_full["complaint_count"] = orders_full["complaint_count"].fillna(0)
orders_full["app_event_count"] = orders_full["app_event_count"].fillna(0)
orders_full["any_high_severity"] = orders_full["any_high_severity"].fillna(0)
orders_full["avg_compensation"] = orders_full["avg_compensation"].fillna(0)

print("Rows:", orders_full.shape[0])
print("Columns:", orders_full.shape[1])
print("Duplicate order_ids:", orders_full["order_id"].duplicated().sum())
print(orders_full[["order_id", "delivery_id", "complaint_count", "app_event_count"]].head(10))
print(orders_full[["complaint_count", "app_event_count", "any_high_severity", "avg_compensation"]].isna().sum())

Rows: 1250
Columns: 56
Duplicate order_ids: 0
  order_id delivery_id  complaint_count  app_event_count
0   O00001     DL00937              0.0              1.0
1   O00002         NaN              0.0              1.0
2   O00003     DL00925              1.0              0.0
3   O00004     DL00002              0.0              0.0
4   O00005     DL00671              1.0              0.0
5   O00006         NaN              0.0              0.0
6   O00007     DL00120              1.0              0.0
7   O00008     DL00201              1.0              1.0
8   O00009     DL00042              0.0              0.0
9   O00010     DL00032              0.0              0.0
complaint_count      0
app_event_count      0
any_high_severity    0
avg_compensation     0
dtype: int64

In [16]:
# Save the final enriched orders table to a CSV file without the index
orders_full.to_csv("orders_full_final.csv", index=False)

In [17]:

df = pd.read_csv("orders_full_final.csv")
# Re-parse datetime columns
for col in ["order_created_at", "dispatch_time", "delivery_completed_at"]:
    if col in df.columns:
        df[col] = pd.to_datetime(df[col], errors="coerce")
print(f"Loaded dataset shape: {df.shape}")

Loaded dataset shape: (1250, 56)

##Section: SQL within R (using rpy2)

###Markdown summary:
An R environment was configured with sqldf, the integrated dataset was loaded, and key derived variables such as actual_hours, delay_hours, and is_delayed were created. SQL queries were then executed within R to analyse operational patterns across zones, services, routes, hubs, drivers, customers, and vehicles, including results such as Central zone’s average delay of 3.00 hours and failure rate of 0.345.

In [18]:
# Load the rpy2 extension
%load_ext rpy2.ipython

In [ ]:
%%R
# Install required R packages (run once)
install.packages(c("sqldf", "dplyr", "ggplot2", "corrplot", "scales", "lubridate", "tidyr", "RColorBrewer"), quiet = TRUE)

In [ ]:
%%R
# Load libraries
library(sqldf)
library(dplyr)
library(ggplot2)
library(corrplot)
library(scales)
library(lubridate)
library(tidyr)
library(RColorBrewer)

# Read the master CSV
df <- read.csv("orders_full_final.csv", stringsAsFactors = FALSE)
cat("Rows:", nrow(df), "Cols:", ncol(df), "\n")

# Convert datetime columns
date_cols <- c("order_created_at", "dispatch_time", "delivery_completed_at")
for (col in date_cols) {
  if (col %in% names(df)) {
    df[[col]] <- as.POSIXct(df[[col]], format="%Y-%m-%d %H:%M:%S", tz="UTC")
  }
}

# Create derived variables
df$actual_hours <- as.numeric(difftime(df$delivery_completed_at, df$dispatch_time, units="hours"))
df$delay_hours  <- df$actual_hours - df$promised_window_hours
df$is_delayed   <- ifelse(df$delivery_status %in% c("Delayed","Failed"), 1L, 0L)
df$order_month  <- floor_date(df$order_created_at, "month")

cat("Derived fields added.\n")

In [ ]:
# Check column names for all your DataFrames
print("=== orders columns ===")
print(orders.columns.tolist())

print("\n=== deliveries columns ===")
print(deliveries.columns.tolist())

print("\n=== customers columns ===")
print(customers.columns.tolist())

print("\n=== complaints columns ===")
print(complaints.columns.tolist())

print("\n=== app_events columns ===")
print(app_events.columns.tolist())

print("\n=== vehicles columns ===")
print(vehicles.columns.tolist())

print("\n=== hubs columns ===")
print(hubs.columns.tolist())

print("\n=== drivers columns ===")
print(drivers.columns.tolist())

In [ ]:
%%R
# Query 1: Delay performance by pickup zone
zone_delay <- sqldf("
  SELECT pickup_zone,
         COUNT(*) AS order_count,
         ROUND(AVG(delay_hours), 2) AS avg_delay_hrs,
         ROUND(SUM(CASE WHEN is_delayed=1 THEN 1.0 ELSE 0 END) / COUNT(*), 3) AS failure_rate
  FROM df
  WHERE delay_hours IS NOT NULL
  GROUP BY pickup_zone
  ORDER BY avg_delay_hrs DESC
")
print("--- Q1: Delay by zone ---")
print(zone_delay)

In [ ]:
%%R
# Query 2: Complaint intensity by service type
complaint_svc <- sqldf("
  SELECT service_type,
         COUNT(*) AS order_count,
         ROUND(AVG(complaint_count), 3) AS avg_complaints,
         ROUND(AVG(avg_compensation), 2) AS avg_comp_paid,
         ROUND(AVG(is_delayed), 3) AS delay_rate
  FROM df
  GROUP BY service_type
  ORDER BY delay_rate DESC
")
print("--- Q2: Complaints by service type ---")
print(complaint_svc)

In [ ]:
%%R
# Query 3: High-override routes
override_routes <- sqldf("
  SELECT pickup_zone || ' → ' || dropoff_zone AS route,
         COUNT(*) AS orders,
         ROUND(AVG(manual_route_override_count), 2) AS avg_overrides,
         ROUND(AVG(delay_hours), 2) AS avg_delay,
         ROUND(AVG(fuel_or_charge_cost), 2) AS avg_cost
  FROM df
  WHERE manual_route_override_count > 0
  GROUP BY route
  ORDER BY avg_overrides DESC
  LIMIT 10
")
print("--- Q3: High-override routes ---")
print(override_routes)

In [ ]:
%%R
# Query 4: Hub-level performance
hub_perf <- sqldf("
  SELECT hub_name,
         COUNT(*) AS orders_dispatched,
         ROUND(AVG(is_delayed), 3) AS delay_rate,
         ROUND(AVG(complaint_count), 3) AS avg_complaints,
         ROUND(AVG(manual_route_override_count), 2) AS avg_overrides,
         ROUND(AVG(order_value), 2) AS avg_order_value,
         ROUND(SUM(fuel_or_charge_cost), 2) AS total_fuel_cost
  FROM df
  GROUP BY hub_name
  ORDER BY orders_dispatched DESC
")
print("--- Q4: Hub-level performance ---")
print(hub_perf)

In [ ]:
%%R
# Query 5: Driver risk profile (top 15 high-override drivers)
driver_risk <- sqldf("
  SELECT driver_id,
         employment_type,
         ROUND(AVG(years_experience), 1) AS avg_experience,
         ROUND(AVG(driver_rating), 2) AS avg_rating,
         ROUND(AVG(training_score), 2) AS avg_training,
         COUNT(*) AS orders_handled,
         ROUND(AVG(manual_route_override_count), 2) AS avg_overrides,
         ROUND(AVG(is_delayed), 3) AS delay_rate
  FROM df
  WHERE driver_id IS NOT NULL
  GROUP BY driver_id, employment_type
  HAVING COUNT(*) >= 3
  ORDER BY avg_overrides DESC
  LIMIT 15
")
print("--- Q5: Top 15 high-override drivers ---")
print(driver_risk)

In [ ]:
%%R
# Query 6: Repeat-complaint customers
repeat_customers <- sqldf("
  SELECT customer_id,
         customer_type,
         home_zone,
         COUNT(*) AS orders,
         ROUND(SUM(complaint_count), 0) AS total_complaints,
         ROUND(AVG(avg_compensation), 2) AS avg_comp_received,
         ROUND(AVG(loyalty_score), 2) AS loyalty_score,
         ROUND(AVG(is_delayed), 3) AS delay_rate
  FROM df
  GROUP BY customer_id, customer_type, home_zone
  HAVING SUM(complaint_count) >= 2
  ORDER BY total_complaints DESC
  LIMIT 15
")
print("--- Q6: Repeat-complaint customers (top 15) ---")
print(repeat_customers)

In [ ]:
%%R
# Query 7: Vehicle maintenance vs delay
vehicle_maint <- sqldf("
  SELECT vehicle_type,
         CASE WHEN maintenance_status = 'InRepair' THEN 'Under Maintenance'
              ELSE 'Operational' END AS maint_status,
         COUNT(*) AS orders,
         ROUND(AVG(delay_hours), 2) AS avg_delay,
         ROUND(AVG(battery_health_pct), 1) AS avg_battery,
         ROUND(AVG(is_delayed), 3) AS delay_rate,
         ROUND(AVG(fuel_or_charge_cost), 2) AS avg_fuel_cost
  FROM df
  WHERE vehicle_type IS NOT NULL
  GROUP BY vehicle_type, maint_status
  ORDER BY vehicle_type, maint_status
")
print("--- Q7: Vehicle maintenance vs delay ---")
print(vehicle_maint)

In [ ]:
# --- Q8: Monthly trend ---

# Create yr_month from order_created_at
orders["yr_month"] = pd.to_datetime(orders["order_created_at"]).dt.to_period("M")

# Merge orders with deliveries to get delay information
orders_with_delivery = orders.merge(
    deliveries[["order_id", "dispatch_time", "delivery_completed_at"]],
    on="order_id",
    how="left"
)

# Calculate delay (if delivery_completed_at exists)
orders_with_delivery["delivery_completed_at"] = pd.to_datetime(orders_with_delivery["delivery_completed_at"])
orders_with_delivery["order_created_at_dt"] = pd.to_datetime(orders_with_delivery["order_created_at"])
orders_with_delivery["promised_deadline"] = orders_with_delivery["order_created_at_dt"] + pd.to_timedelta(orders_with_delivery["promised_window_hours"], unit="h")
orders_with_delivery["delay_hours"] = (orders_with_delivery["delivery_completed_at"] - orders_with_delivery["promised_deadline"]).dt.total_seconds() / 3600

# Count complaints per order
complaints_per_order = complaints.groupby("order_id").size().reset_index(name="complaint_count")

monthly_trend = (
    orders_with_delivery.merge(complaints_per_order, on="order_id", how="left")
    .groupby("yr_month")
    .agg(
        orders=("order_id", "count"),
        delay_rate=("delay_hours", lambda x: (x > 0).mean()),  # % of orders with delay > 0
        avg_value=("order_value", "mean"),
        avg_complaints=("complaint_count", "mean")  # avg complaints per order
    )
    .reset_index()
)

# Format yr_month as string for display
monthly_trend["yr_month"] = monthly_trend["yr_month"].astype(str)

print(monthly_trend)

In [ ]:
%%R
# Query 9: INSERT, UPDATE, DELETE demonstrations
# INSERT equivalent: escalation log
escalation_log <- sqldf("
  SELECT order_id,
         'High delay + complaint' AS flag_reason,
         datetime('now') AS flagged_at
  FROM df
  WHERE delay_hours > 5 AND complaint_count >= 1
  LIMIT 10
")
print("--- Q9a: INSERT — escalation log sample ---")
print(escalation_log)

# UPDATE equivalent: reclassify borderline deliveries
df_update_demo <- df %>%
  mutate(delivery_status_revised = case_when(
    delivery_status == "OnTime" & delay_hours > 0.5 ~ "Borderline",
    TRUE ~ delivery_status
  ))
print("--- Q9b: UPDATE — borderline reclassification ---")
print(table(df_update_demo$delivery_status_revised, useNA = "ifany"))

# DELETE equivalent: keep only rows with non‑null delivery_id
df_clean <- sqldf("SELECT * FROM df WHERE delivery_id IS NOT NULL AND delivery_id != ''")
cat("--- Q9c: DELETE equivalent — rows with delivery_id ---\n")
cat("Rows kept:", nrow(df_clean), "of", nrow(df), "\n")

In [ ]:
%%R
# Mathematical and aggregate functions: overall summary
summary_stats <- sqldf("
  SELECT COUNT(*) AS total_orders,
         ROUND(AVG(order_value), 2) AS mean_order_value,
         ROUND(MIN(order_value), 2) AS min_order_value,
         ROUND(MAX(order_value), 2) AS max_order_value,
         ROUND(SUM(order_value), 2) AS total_revenue,
         ROUND(AVG(delay_hours), 2) AS mean_delay_hrs,
         ROUND(AVG(route_distance_km), 2) AS mean_route_km,
         ROUND(AVG(fuel_or_charge_cost), 2) AS mean_fuel_cost,
         ROUND(SUM(fuel_or_charge_cost), 2) AS total_fuel_cost,
         ROUND(AVG(complaint_count), 4) AS mean_complaints_per_order,
         ROUND(SUM(complaint_count), 0) AS total_complaints,
         ROUND(SUM(avg_compensation), 2) AS total_compensation_paid
  FROM df
")
print("--- Operational Summary Statistics ---")
print(t(summary_stats))

# Cost per km by vehicle type
cost_per_km <- sqldf("
  SELECT vehicle_type,
         COUNT(*) AS orders,
         ROUND(SUM(fuel_or_charge_cost), 2) AS total_cost,
         ROUND(SUM(route_distance_km), 2) AS total_km,
         ROUND(SUM(fuel_or_charge_cost)/SUM(route_distance_km), 3) AS cost_per_km
  FROM df
  WHERE route_distance_km > 0
  GROUP BY vehicle_type
  ORDER BY cost_per_km DESC
")
print("--- Cost per km by vehicle type ---")
print(cost_per_km)

##Statistical Validation

In [ ]:
%%R
# Filter for Central and South zones (non‑missing delay_hours)
central_delays <- df$delay_hours[df$pickup_zone == "Central" & !is.na(df$delay_hours)]
south_delays <- df$delay_hours[df$pickup_zone == "South" & !is.na(df$delay_hours)]

cat("Central zone delay hours (n=", length(central_delays), "): mean =", round(mean(central_delays),2), ", sd =", round(sd(central_delays),2), "\n")
cat("South zone delay hours (n=", length(south_delays), "): mean =", round(mean(south_delays),2), ", sd =", round(sd(south_delays),2), "\n")

In [ ]:
%%R
# Perform t-test assuming unequal variance (Welch's test)
t_test_result <- t.test(central_delays, south_delays, alternative = "two.sided", var.equal = FALSE)
print(t_test_result)

# Extract key values for reporting
cat("\n--- Summary for Report ---\n")
cat("t-statistic:", round(t_test_result$statistic, 2), "\n")
cat("p-value:", format(t_test_result$p.value, scientific = FALSE), "\n")
cat("Degrees of freedom:", round(t_test_result$parameter, 2), "\n")
cat("95% confidence interval:", round(t_test_result$conf.int[1], 2), "to", round(t_test_result$conf.int[2], 2), "\n")

In [ ]:
%%R
contingency_table <- table(df$service_type, df$is_delayed)
print("Contingency table (service_type rows, is_delayed columns):")
print(contingency_table)

chi_test <- chisq.test(contingency_table)
print(chi_test)

In [ ]:
%%R
library(ggplot2)
library(dplyr)

# Calculate delay rate and 95% CI for each service type
delay_props <- df %>%
  filter(!is.na(service_type), !is.na(is_delayed)) %>%
  group_by(service_type) %>%
  summarise(
    delay_rate = mean(is_delayed, na.rm = TRUE),
    n = n(),
    se = sqrt(delay_rate * (1 - delay_rate) / n),
    lower = delay_rate - 1.96 * se,
    upper = delay_rate + 1.96 * se
  )

# Bar chart with error bars
p <- ggplot(delay_props, aes(x = reorder(service_type, -delay_rate), y = delay_rate, fill = service_type)) +
  geom_col(width = 0.7) +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +
  scale_y_continuous(labels = scales::percent, limits = c(0, 0.45)) +
  labs(
    title = "Delay Rate by Service Type (with 95% Confidence Interval)",
    subtitle = "No statistically significant association (χ² = 3.66, p = 0.454)",
    x = "Service Type", y = "Delay Rate (%)",
    caption = "Error bars = 95% confidence interval"
  ) +
  theme_minimal() +
  theme(legend.position = "none")

print(p)

##Section: R Analytics and Visualisation
###Markdown summary:
I produce all eight visualisations described in the report: delay boxplot by zone, failure rate bar chart by service type, hub performance heatmap, monthly delay trend, correlation matrix, value vs delay scatter, override by employment violin, and proof missing bar chart.

In [ ]:
%%R
# Load required libraries
library(dplyr)
library(ggplot2)
library(corrplot)
library(scales)
library(lubridate)
library(tidyr)
library(RColorBrewer)

# Read the master CSV (if not already loaded)
df <- read.csv("orders_full_final.csv", stringsAsFactors = FALSE)

# Convert datetime columns
date_cols <- c("order_created_at", "dispatch_time", "delivery_completed_at")
for (col in date_cols) {
  if (col %in% names(df)) {
    df[[col]] <- as.POSIXct(df[[col]], format="%Y-%m-%d %H:%M:%S", tz="UTC")
  }
}

# Create derived variables
df$actual_hours <- as.numeric(difftime(df$delivery_completed_at, df$dispatch_time, units="hours"))
df$delay_hours  <- df$actual_hours - df$promised_window_hours
df$is_delayed   <- ifelse(df$delivery_status %in% c("Delayed","Failed"), 1L, 0L)
df$order_month  <- floor_date(df$order_created_at, "month")

# Define NorthStar theme
theme_northstar <- theme_minimal(base_size = 13) +
  theme(
    plot.title    = element_text(face="bold", size=14, hjust=0),
    plot.subtitle = element_text(size=11, color="#555555"),
    axis.text     = element_text(color="#333333"),
    panel.grid.minor = element_blank()
  )

cat("Setup complete. Dataset rows:", nrow(df), "\n")

In [ ]:
%%R -h 600 -w 900
# Filter extreme delay values for cleaner visualization
df_plot <- df %>% filter(!is.na(delay_hours), delay_hours > -10, delay_hours < 30)

# Figure 1: Delay by zone boxplot
p1 <- ggplot(df_plot, aes(x=reorder(pickup_zone, delay_hours, median),
                          y=delay_hours, fill=pickup_zone)) +
  geom_boxplot(outlier.alpha=0.3, outlier.size=1) +
  coord_flip() +
  scale_fill_brewer(palette="Set2") +
  labs(title = "Figure 1: Delivery Delay Distribution by Pickup Zone",
       subtitle = "Positive values = over promised window; Central and Riverside show worst spread",
       x = "Zone", y = "Delay (hours above promise)",
       caption = "Source: orders_full_final.csv — NorthStar Master Dataset") +
  theme_northstar +
  theme(legend.position="none")

print(p1)

In [ ]:
%%R -h 600 -w 900
# Summarize delay rate by service type
svc_summary <- df %>%
  group_by(service_type) %>%
  summarise(delay_rate = mean(is_delayed, na.rm=TRUE),
            order_count = n(),
            avg_value = mean(order_value, na.rm=TRUE)) %>%
  ungroup()

# Figure 2: delay rate by service type
p2 <- ggplot(svc_summary, aes(x=reorder(service_type, delay_rate),
                              y=delay_rate, fill=delay_rate)) +
  geom_col(width=0.6) +
  geom_text(aes(label=percent(delay_rate, accuracy=0.1)),
            hjust=-0.1, size=4) +
  coord_flip(ylim=c(0, 0.42)) +
  scale_fill_gradient(low="#f7c59f", high="#d62728") +
  labs(title = "Figure 2: Failure/Delay Rate by Service Type",
       subtitle = "Business and Medical orders are most operationally at-risk",
       x = NULL, y = "Proportion delayed or failed",
       caption = "OnTime + Delayed + Failed = delivery_status") +
  theme_northstar +
  theme(legend.position="none")

print(p2)

In [ ]:
%%R -h 700 -w 1000
# Hub-level matrix of failure-related metrics
hub_matrix <- df %>%
  group_by(hub_name) %>%
  summarise(delay_rate = mean(is_delayed, na.rm=TRUE),
            avg_overrides = mean(manual_route_override_count, na.rm=TRUE),
            avg_complaints = mean(complaint_count, na.rm=TRUE),
            proof_missing = mean(proof_of_completion_missing, na.rm=TRUE)) %>%
  ungroup()

# Convert to long format for heatmap
hub_long <- hub_matrix %>%
  pivot_longer(-hub_name, names_to="metric", values_to="value")

# Figure 3: hub performance heatmap
p3 <- ggplot(hub_long, aes(x=metric, y=hub_name, fill=value)) +
  geom_tile(color="white", linewidth=0.5) +
  geom_text(aes(label=round(value,2)), size=3.5) +
  scale_fill_gradient(low="#edf8fb", high="#006d77") +
  labs(title = "Figure 3: Hub Performance Heatmap",
       subtitle = "Midtown Relay and Riverside Hub stand out across multiple failure metrics",
       x = "Performance Metric", y = "Hub",
       fill = "Score") +
  theme_northstar +
  theme(axis.text.x = element_text(angle=25, hjust=1))

print(p3)

In [ ]:
%%R -h 600 -w 950
# Prepare monthly delay-rate time series
monthly_r <- df %>%
  filter(!is.na(order_created_at)) %>%
  mutate(yr_month = floor_date(order_created_at, "month")) %>%
  group_by(yr_month) %>%
  summarise(delay_rate = mean(is_delayed, na.rm=TRUE),
            order_count = n()) %>%
  ungroup() %>%
  filter(order_count >= 5)

# Figure 4: monthly delay-rate trend
p4 <- ggplot(monthly_r, aes(x=yr_month, y=delay_rate)) +
  geom_line(color="#006d77", linewidth=1.2) +
  geom_point(aes(size=order_count), color="#e29578", alpha=0.8) +
  geom_smooth(method="lm", se=TRUE, color="#d62728", linetype="dashed",
              linewidth=0.8) +
  scale_y_continuous(labels=percent_format(accuracy=1)) +
  scale_x_datetime(date_labels="%b %Y") +
  labs(title = "Figure 4: Monthly Delay Rate Trend",
       subtitle = "Trendline indicates worsening service reliability over time",
       x = NULL, y = "Delay/Failure Rate",
       size = "Orders that month",
       caption = "Point size = number of orders that month") +
  theme_northstar

print(p4)

In [ ]:
%%R -h 800 -w 1000
# Select core continuous variables and drop rows with missing values
cor_vars <- df %>%
  select(delay_hours, order_value, route_distance_km,
         manual_route_override_count, fuel_or_charge_cost,
         battery_health_pct, driver_rating, training_score,
         loyalty_score, complaint_count) %>%
  filter(complete.cases(.))

# Compute correlation matrix
cor_matrix <- cor(cor_vars)

# Figure 5: polished correlation matrix
corrplot(cor_matrix,
         method = "color",
         type = "upper",
         addCoef.col = "black",
         tl.col = "black",
         tl.cex = 1.1,
         tl.srt = 45,
         number.cex = 0.85,
         number.digits = 2,
         col = colorRampPalette(c("#d62728","white","#006d77"))(200),
         title = "Figure 5: Operational Variable Correlation Matrix\n(Upper Triangle, r values)",
         mar = c(2,2,4,2))

In [ ]:
%%R -h 650 -w 1100
# Figure 6: value-vs-delay scatterplot by service type
p6 <- df %>%
  filter(!is.na(delay_hours), !is.na(order_value),
         delay_hours > -5, delay_hours < 25) %>%
  ggplot(aes(x=order_value, y=delay_hours,
             color=service_type, alpha=0.7)) +
  geom_point(size=1.4) +
  geom_smooth(method="lm", se=FALSE, linewidth=1) +
  facet_wrap(~service_type, ncol=3) +
  scale_color_brewer(palette="Dark2") +
  labs(title = "Figure 6: Order Value vs Delay by Service Type",
       subtitle = "Higher-value Business and Medical orders do not receive priority routing",
       x = "Order Value (£)", y = "Delay (hours)") +
  theme_northstar +
  theme(legend.position="none")

print(p6)

In [ ]:
%%R -h 600 -w 900
# Figure 7: route override distribution by driver employment type
p7 <- df %>%
  filter(!is.na(employment_type)) %>%
  ggplot(aes(x=employment_type,
             y=manual_route_override_count,
             fill=employment_type)) +
  geom_violin(trim=FALSE, alpha=0.7) +
  geom_boxplot(width=0.12, fill="white", outlier.size=0.8) +
  scale_fill_brewer(palette="Pastel1") +
  labs(title = "Figure 7: Route Override Frequency by Driver Employment Type",
       subtitle = "Contract drivers show a wider spread — inconsistency vs full-time staff",
       x = "Employment Type", y = "Manual Route Overrides per Delivery") +
  theme_northstar +
  theme(legend.position="none")

print(p7)

In [ ]:
%%R -h 600 -w 900
# Compute proof-of-completion missing rate by pickup zone
proof_zone <- df %>%
  filter(!is.na(proof_of_completion_missing)) %>%
  group_by(pickup_zone) %>%
  summarise(pct_missing = mean(proof_of_completion_missing, na.rm=TRUE)) %>%
  ungroup()

# Figure 8: missing-proof bar chart by zone
p8 <- ggplot(proof_zone, aes(x=reorder(pickup_zone, pct_missing),
                             y=pct_missing, fill=pct_missing)) +
  geom_col(width=0.6) +
  geom_text(aes(label=percent(pct_missing, accuracy=0.1)),
            hjust=-0.1, size=4) +
  coord_flip(ylim=c(0, max(proof_zone$pct_missing)*1.2)) +
  scale_fill_gradient(low="#fee8c8", high="#d7301f") +
  labs(title = "Figure 8: Proof-of-Completion Missing Rate by Zone",
       subtitle = "Missing proof creates disputes, liability exposure, and data gaps in MongoDB redesign",
       x = NULL, y = "Proportion with missing proof") +
  theme_northstar +
  theme(legend.position="none")

print(p8)

##Section 2: Python Data Processing and Operational Analytics
###Markdown summary:
I reload the master CSV, perform extensive feature engineering (delay categories, route risk score, customer risk segmentation, hub efficiency score, etc.), then use NumPy and Pandas to compute descriptive statistics, zone summaries, hub rankings, customer risk segments, and fleet health.

In [ ]:
# Reload and re-parse dates
df = pd.read_csv("orders_full_final.csv")
for col in ["order_created_at", "dispatch_time", "delivery_completed_at"]:
    if col in df.columns:
        df[col] = pd.to_datetime(df[col], errors="coerce")

# ---- Feature engineering ----
# Actual delivery hours and delay
df["actual_delivery_hrs"] = (df["delivery_completed_at"] - df["dispatch_time"]).dt.total_seconds() / 3600
df["delay_hours"] = df["actual_delivery_hrs"] - df["promised_window_hours"]

# Delay categories
bins = [-np.inf, -1, 0, 2, 6, np.inf]
labels = ["Early", "On-Time", "Minor Delay", "Significant Delay", "Critical Delay"]
df["delay_category"] = pd.cut(df["delay_hours"], bins=bins, labels=labels)

# Binary flags
df["is_delayed"] = df["delivery_status"].isin(["Delayed", "Failed"]).astype(int)
df["is_failed"] = (df["delivery_status"] == "Failed").astype(int)
df["complaint_flag"] = (df["complaint_count"] >= 1).astype(int)

# Repeated high severity
high_sev_cust = df.groupby("customer_id")["any_high_severity"].sum().reset_index()
high_sev_cust.columns = ["customer_id", "total_high_sev"]
df = df.merge(high_sev_cust, on="customer_id", how="left")
df["repeated_high_severity"] = (df["total_high_sev"] >= 2).astype(int)

# Route risk score (min-max scaled)
def minmax(series):
    r = series.max() - series.min()
    return (series - series.min()) / r if r > 0 else series * 0

route_stats = df.groupby(["pickup_zone", "dropoff_zone"]).agg(
    route_delay_rate = ("is_delayed", "mean"),
    route_avg_override = ("manual_route_override_count", "mean"),
    route_avg_complaint = ("complaint_count", "mean")
).reset_index()
route_stats["route_risk_score"] = (
    0.40 * minmax(route_stats["route_delay_rate"]) +
    0.35 * minmax(route_stats["route_avg_override"]) +
    0.25 * minmax(route_stats["route_avg_complaint"])
)
df = df.merge(route_stats[["pickup_zone", "dropoff_zone", "route_risk_score"]],
              on=["pickup_zone", "dropoff_zone"], how="left")

# Driver override percentile
override_pct = df.groupby("driver_id")["manual_route_override_count"].mean()
df["driver_override_pctile"] = df["driver_id"].map(override_pct.rank(pct=True))

# Vehicle age
if "commission_date_x" in df.columns:
    df["commission_date"] = df["commission_date_x"]
if "commission_date" in df.columns:
    df["commission_date"] = pd.to_datetime(df["commission_date"], errors="coerce")
    df["vehicle_age_days"] = (pd.Timestamp("2025-01-01") - df["commission_date"]).dt.days
else:
    df["vehicle_age_days"] = np.nan

# In-repair flag
if "maintenance_status" in df.columns:
    df["maintenance_status"] = df["maintenance_status"].astype(str)
    df["in_repair_flag"] = (df["maintenance_status"] == "InRepair").astype(int)
else:
    df["in_repair_flag"] = np.nan

# Hub failure rate
hub_fail = df.groupby("hub_name")["is_delayed"].mean().rename("hub_failure_rate")
df = df.join(hub_fail, on="hub_name")

# Customer risk segment
df["customer_risk_segment"] = np.select(
    [
        (df["loyalty_score"] >= 7) & (df["complaint_flag"] == 1),
        (df["loyalty_score"] >= 7) & (df["complaint_flag"] == 0),
        (df["loyalty_score"] < 7) & (df["complaint_flag"] == 1),
    ],
    ["High-Value At-Risk", "High-Value Stable", "Low-Value Dissatisfied"],
    default="Low-Value Stable"
)

print("Feature engineering complete. New columns added:")
new_cols = ["delay_hours", "delay_category", "is_delayed", "is_failed", "complaint_flag",
            "repeated_high_severity", "route_risk_score", "driver_override_pctile",
            "vehicle_age_days", "hub_failure_rate", "customer_risk_segment", "in_repair_flag"]
print(new_cols)
print(df[new_cols].describe(include="all").T[["count", "mean", "std", "min", "max"]].to_string())

In [ ]:
new_features = [
    'delay_hours', 'delay_category', 'is_delayed', 'is_failed',
    'complaint_flag', 'repeated_high_severity', 'route_risk_score',
    'driver_override_pctile', 'vehicle_age_days', 'hub_failure_rate',
    'customer_risk_segment', 'in_repair_flag'
]

print("Missing features:", [c for c in new_features if c not in df.columns])

existing_features = [c for c in new_features if c in df.columns]
print("\nMissing values:")
print(df[existing_features].isna().sum().to_string())

print("\nBinary feature counts:")
for col in ['is_delayed', 'is_failed', 'complaint_flag', 'repeated_high_severity', 'in_repair_flag']:
    if col in df.columns:
        print(f"{col}: {df[col].value_counts(dropna=False).to_dict()}")

print("\nCategorical feature counts:")
for col in ['delay_category', 'customer_risk_segment']:
    if col in df.columns:
        print(f"{col}: {df[col].value_counts(dropna=False).to_dict()}")

print("\nKey numeric summaries:")
for col in ['vehicle_age_days', 'delay_hours', 'hub_failure_rate']:
    if col in df.columns:
        s = df[col]
        print(f"{col}: count={s.count()}, mean={s.mean():.3f}, min={s.min():.3f}, max={s.max():.3f}")

In [ ]:
# ---- NumPy descriptive statistics ----
num_cols = [
    "delay_hours", "order_value", "route_distance_km", "fuel_or_charge_cost",
    "manual_route_override_count", "battery_health_pct", "driver_rating",
    "training_score", "loyalty_score", "app_engagement_score"
]
arr = df[num_cols].dropna().to_numpy()
print("NumPy array shape:", arr.shape)
print("Column means  :", np.round(np.nanmean(arr, axis=0), 3))
print("Column medians:", np.round(np.median(arr, axis=0), 3))
print("Column std    :", np.round(np.nanstd(arr, axis=0), 3))
print("Column min    :", np.round(np.nanmin(arr, axis=0), 3))
print("Column max    :", np.round(np.nanmax(arr, axis=0), 3))

# ---- Zone-level operational summary ----
zone_summary = (
    df.groupby("pickup_zone")
    .agg(
        orders=("order_id", "count"),
        avg_delay_hrs=("delay_hours", "mean"),
        delay_rate=("is_delayed", "mean"),
        avg_overrides=("manual_route_override_count", "mean"),
        avg_order_value=("order_value", "mean"),
        total_revenue=("order_value", "sum"),
        total_fuel_cost=("fuel_or_charge_cost", "sum"),
        avg_complaints=("complaint_count", "mean")
    )
    .round(3)
    .sort_values("avg_delay_hrs", ascending=False)
    .reset_index()
)
print("\n--- Zone-level operational summary ---")
print(zone_summary.to_string(index=False))

In [ ]:
# ---- Hub efficiency score ----
hub_metrics = df.groupby('hub_name').agg(
    delay_rate=('is_delayed', 'mean'),
    overrides_rate=('manual_route_override_count', 'mean'),
    proof_missing_rate=('proof_of_completion_missing', 'mean')
).reset_index()
hub_metrics['efficiency_score'] = (
    0.40 * (1 - hub_metrics['delay_rate']) +
    0.35 * (1 - hub_metrics['overrides_rate']) +
    0.25 * (1 - hub_metrics['proof_missing_rate'])
)
print("\n--- Hub efficiency score ranking ---")
result = hub_metrics.sort_values('efficiency_score', ascending=False)[
    ['hub_name', 'efficiency_score', 'delay_rate', 'overrides_rate', 'proof_missing_rate']
].round(3)
print(result)
print(f"\nTop performer: {result.iloc[0]['hub_name']} (score: {result.iloc[0]['efficiency_score']:.3f})")

In [ ]:
# ---- Customer risk segment analysis ----
seg_analysis = (
    df.groupby("customer_risk_segment")
    .agg(
        customers=("customer_id", "nunique"),
        orders=("order_id", "count"),
        avg_loyalty=("loyalty_score", "mean"),
        avg_delay=("delay_hours", "mean"),
        avg_revenue=("order_value", "mean"),
        total_revenue=("order_value", "sum"),
        complaint_rate=("complaint_flag", "mean")
    )
    .round(3)
    .reset_index()
)
print("\n--- Customer risk segment analysis ---")
print(seg_analysis.to_string(index=False))

In [ ]:
# ---- Top 10 highest-risk routes ----
top_routes = (
    df.groupby(["pickup_zone", "dropoff_zone", "route_risk_score"])
    .agg(
        orders=("order_id", "count"),
        delay_rate=("is_delayed", "mean"),
        avg_override=("manual_route_override_count", "mean"),
        avg_delay=("delay_hours", "mean")
    )
    .round(3)
    .reset_index()
    .sort_values("route_risk_score", ascending=False)
    .head(10)
)
print("\n--- Top 10 highest-risk routes ---")
print(top_routes.to_string(index=False))

In [ ]:
# ---- Fleet health by vehicle type ----
fleet_health = (
    df.groupby("vehicle_type")
    .agg(
        orders=("order_id", "count"),
        avg_battery=("battery_health_pct", "mean"),
        avg_delay=("delay_hours", "mean"),
        avg_vehicle_age=("vehicle_age_days", "mean"),
        maint_rate=("in_repair_flag", "mean"),
        avg_fuel_cost=("fuel_or_charge_cost", "mean")
    )
    .round(3)
    .reset_index()
)
print("\n--- Fleet health by vehicle type ---")
print(fleet_health.to_string(index=False))

In [ ]:
# ---- Pairplot (six core metrics, coloured by service type) ----
pair_cols = ["delay_hours", "order_value", "route_distance_km",
             "manual_route_override_count", "fuel_or_charge_cost", "driver_rating"]
pair_df = df[pair_cols + ["service_type"]].dropna()
pair_df = pair_df[
    (pair_df["delay_hours"].between(-5, 25)) & (pair_df["route_distance_km"] > 0)
].sample(min(600, len(pair_df)), random_state=42)

fig_pair = sns.pairplot(pair_df, hue="service_type", palette="tab10",
                        plot_kws={"alpha": 0.5, "s": 25}, diag_kind="kde", corner=True)
fig_pair.fig.suptitle("Pairwise Relationships — Core Operational Metrics\n(coloured by service type)",
                      y=1.02, fontsize=13, fontweight="bold")
plt.tight_layout()
plt.savefig("fig_pairplot.png", bbox_inches="tight")
plt.show()

In [ ]:
# ---- Extended correlation heatmap ----
heat_cols = [
    "delay_hours", "order_value", "route_distance_km", "manual_route_override_count",
    "fuel_or_charge_cost", "battery_health_pct", "driver_rating", "training_score",
    "loyalty_score", "app_engagement_score", "complaint_count", "vehicle_age_days",
    "hub_failure_rate", "route_risk_score"
]
corr_df = df[heat_cols].dropna()
corr_matrix = corr_df.corr()
mask = np.triu(np.ones_like(corr_matrix, dtype=bool))
plt.figure(figsize=(12, 9))
sns.heatmap(corr_matrix, mask=mask, annot=True, fmt=".2f", cmap="RdYlBu_r",
            center=0, linewidths=0.4, linecolor="white", annot_kws={"size": 8})
plt.title("Correlation Heatmap — Operational Variables\n(lower triangle; red = positive, blue = negative correlation)", pad=12)
plt.tight_layout()
plt.savefig("fig_heatmap.png", bbox_inches="tight")
plt.show()

In [ ]:
# ---- Delay category stacked bar by zone ----
import matplotlib.ticker as mtick

cat_order = ["Early", "On-Time", "Minor Delay", "Significant Delay", "Critical Delay"]
cat_pivot = (df[df["delay_category"].notna()]
             .groupby(["pickup_zone", "delay_category"], observed=True)
             .size()
             .unstack("delay_category", fill_value=0)
             .reindex(columns=cat_order, fill_value=0))
cat_pct = cat_pivot.div(cat_pivot.sum(axis=1), axis=0)

fig_stack, ax = plt.subplots(figsize=(10, 6))
colors = ["#2a9d8f", "#57cc99", "#ffd166", "#ef9b20", "#e63946"]
cat_pct.plot(kind="bar", stacked=True, color=colors, ax=ax, width=0.7)
ax.yaxis.set_major_formatter(mtick.PercentFormatter(1.0))
ax.set_xlabel("Pickup Zone")
ax.set_ylabel("Proportion of Orders")
ax.set_title("Delivery Delay Category Distribution by Zone\nCentral zone shows highest Critical Delay share", pad=15)
ax.legend(title="Delay Category", bbox_to_anchor=(1.01, 1), loc="upper left")
plt.xticks(rotation=30, ha="right")
plt.tight_layout()
plt.savefig("fig11_delay_stacked.png", bbox_inches="tight")
plt.show()

In [ ]:
# ---- Route risk vs hub failure rate scatter (coloured by delay) ----
scatter_df = df[["pickup_zone", "route_risk_score", "hub_failure_rate", "delay_hours", "service_type"]].dropna()
fig_sc, ax = plt.subplots(figsize=(9, 6))
sc = ax.scatter(
    scatter_df["route_risk_score"],
    scatter_df["hub_failure_rate"],
    c=scatter_df["delay_hours"].clip(-2, 20),
    cmap="YlOrRd", alpha=0.5, s=35, edgecolors="none"
)
plt.colorbar(sc, ax=ax, label="Delay Hours")
ax.set_xlabel("Route Risk Score (engineered)")
ax.set_ylabel("Hub Failure Rate")
ax.set_title("Route Risk vs Hub Failure Rate\n(colour = delay hours; top-right = highest combined risk)", pad=15)
plt.tight_layout()
plt.savefig("fig_risk_scatter.png", bbox_inches="tight")
plt.show()

##Section3: MongoDB Atlas Design and Implementation
##Markdown summary:
I connect to MongoDB Atlas, design an embedded document structure (customer_cases), insert the enriched data, perform CRUD operations (FIND, UPDATE, DELETE), run aggregation pipelines, and demonstrate query optimisation with indexes and explain plans.

In [ ]:
# Install pymongo and dnspython
!pip install pymongo dnspython --quiet

from pymongo import MongoClient, ASCENDING, DESCENDING
from pymongo.errors import DuplicateKeyError
from datetime import datetime

# Replace with your actual MongoDB Atlas URI
MONGO_URI = "mongodb+srv://amaan44633_db_user:AFm9847king@northstar.pxqjnh4.mongodb.net/?appName=Northstar"
try:
    client = MongoClient(MONGO_URI, serverSelectionTimeoutMS=10000)
    client.admin.command("ping")
    db = client["northstar_db"]
    print("Connected to MongoDB Atlas successfully.")
except Exception as e:
    print(f"Connection failed: {e}")
    raise

In [ ]:
# Build the document structure for each order
def build_service_case(row):
    return {
        "order_id": row["order_id"],
        "customer_id": row["customer_id"],
        "service_type": row.get("service_type"),
        "order_created_at": str(row.get("order_created_at", "")),
        "priority_level": row.get("priority_level"),
        "booking_channel": row.get("booking_channel"),
        "delivery": {
            "delivery_id": row.get("delivery_id"),
            "driver_id": row.get("driver_id"),
            "vehicle_id": row.get("vehicle_id"),
            "hub_id": row.get("hub_id"),
            "hub_name": row.get("hub_name"),
            "dispatch_time": str(row.get("dispatch_time", "")),
            "completed_at": str(row.get("delivery_completed_at", "")),
            "status": row.get("delivery_status"),
            "route_distance_km": row.get("route_distance_km"),
            "overrides": row.get("manual_route_override_count"),
            "rating": row.get("customer_rating_post_delivery"),
            "fuel_cost": row.get("fuel_or_charge_cost"),
            "proof_missing": bool(row.get("proof_of_completion_missing", 0))
        },
        "zone_context": {
            "pickup_zone": row.get("pickup_zone"),
            "dropoff_zone": row.get("dropoff_zone"),
            "home_zone": row.get("home_zone")
        },
        "complaints": {
            "count": int(row.get("complaint_count", 0)),
            "any_high_sev": bool(row.get("any_high_severity", 0)),
            "avg_compensation": row.get("avg_compensation"),
            "last_date": str(row.get("last_complaint_date", ""))
        },
        "app_events_summary": {
            "event_count": int(row.get("app_event_count", 0)),
            "unique_event_types": row.get("unique_event_types"),
            "avg_api_latency_ms": row.get("avg_api_latency"),
            "last_event": str(row.get("last_app_event", ""))
        },
        "risk_tags": {
            "is_delayed": bool(row.get("is_delayed", 0)),
            "complaint_flag": bool(row.get("complaint_flag", 0)),
            "route_risk_score": row.get("route_risk_score"),
            "delay_category": str(row.get("delay_category", ""))
        },
        "inserted_at": datetime.utcnow()
    }

# Insert all documents
collection = db["customer_cases"]
collection.drop()  # fresh start
service_docs = df.apply(build_service_case, axis=1).tolist()
result = collection.insert_many(service_docs)
print(f"Inserted {len(result.inserted_ids)} documents into 'customer_cases'")

In [ ]:
# ---- FIND operations ----
print("\n--- FIND: All failed deliveries in Central zone ---")
failed_central = list(collection.find(
    {"delivery.status": "Failed", "zone_context.pickup_zone": "Central"},
    {"order_id": 1, "delivery.status": 1, "delivery.hub_name": 1, "complaints.count": 1, "_id": 0}
).limit(5))
for doc in failed_central:
    print(doc)

print("\n--- FIND: High-severity complaints with compensation ---")
high_sev = list(collection.find(
    {"complaints.any_high_sev": True, "complaints.avg_compensation": {"$gt": 0}},
    {"order_id": 1, "service_type": 1, "complaints.count": 1, "complaints.avg_compensation": 1, "_id": 0}
).sort("complaints.avg_compensation", DESCENDING).limit(5))
for doc in high_sev:
    print(doc)

print("\n--- FIND: Orders with >2 route overrides AND delayed ---")
override_delayed = list(collection.find(
    {"delivery.overrides": {"$gt": 2}, "risk_tags.is_delayed": True},
    {"order_id": 1, "delivery.overrides": 1, "delivery.driver_id": 1, "zone_context.pickup_zone": 1, "_id": 0}
).limit(5))
for doc in override_delayed:
    print(doc)

In [ ]:
# ---- UPDATE: flag critical cases for review ----
result_update = collection.update_many(
    {"risk_tags.delay_category": {"$in": ["Significant Delay", "Critical Delay"]},
     "complaints.any_high_sev": True},
    {"$set": {"escalation_flag": "REVIEW_REQUIRED", "updated_at": datetime.utcnow()}}
)
print(f"Matched: {result_update.matched_count}, Modified: {result_update.modified_count}")

In [ ]:
# ---- DELETE: remove documents with null delivery_id (if any) ----
result_delete = collection.delete_many({"delivery.delivery_id": None})
print(f"Deleted {result_delete.deleted_count} documents with null delivery_id")

In [ ]:
# ---- AGGREGATION: delay rate and compensation by zone ----
pipeline = [
    {"$group": {
        "_id": "$zone_context.pickup_zone",
        "total_orders": {"$sum": 1},
        "delayed_orders": {"$sum": {"$cond": ["$risk_tags.is_delayed", 1, 0]}},
        "avg_compensation": {"$avg": "$complaints.avg_compensation"},
        "total_complaints": {"$sum": "$complaints.count"},
        "avg_latency_ms": {"$avg": "$app_events_summary.avg_api_latency_ms"}
    }},
    {"$addFields": {"delay_rate": {"$divide": ["$delayed_orders", "$total_orders"]}}},
    {"$sort": {"delay_rate": -1}}
]
agg_results = list(collection.aggregate(pipeline))
print("\n--- Aggregation: Delay rate and avg compensation by zone ---")
for r in agg_results:
    print(r)

##Section: Query Optimisation and Performance Tuning
###Markdown summary:
I create indexes on frequently queried fields, compare explain() output before and after indexing, and document the performance improvement (COLLSCAN → IXSCAN).

In [ ]:
# Before indexing: explain plan
query = {
    "zone_context.pickup_zone": "Central",
    "risk_tags.is_delayed": True,
    "complaints.any_high_sev": True
}
print("--- BEFORE indexing ---")
explain_before = collection.find(query).explain()
print("Stage:", explain_before["queryPlanner"]["winningPlan"]["stage"])
if "executionStats" in explain_before:
    print("Docs examined:", explain_before["executionStats"]["totalDocsExamined"])
    print("Execution ms:", explain_before["executionStats"]["executionTimeMillis"])
else:
    print("(executionStats not available in free tier)")

In [ ]:
# Create indexes
print("\n--- Creating indexes ---")
collection.create_index(
    [("zone_context.pickup_zone", ASCENDING),
     ("risk_tags.is_delayed", ASCENDING),
     ("complaints.any_high_sev", ASCENDING)],
    name="zone_delay_complaint_idx"
)
collection.create_index([("delivery.driver_id", ASCENDING)], name="driver_id_idx")
collection.create_index([("delivery.hub_name", ASCENDING)], name="hub_name_idx")
collection.create_index([("order_id", ASCENDING)], unique=True, name="order_id_unique_idx")
collection.create_index([("inserted_at", DESCENDING)], name="inserted_at_desc_idx")
print("All indexes created.")

# List indexes
print("\nIndexes on customer_cases:")
for idx in collection.list_indexes():
    print(f"  {idx['name']} -> {idx['key']}")

In [ ]:
# After indexing: explain plan
print("\n--- AFTER indexing ---")
explain_after = collection.find(query).explain()
print("Stage:", explain_after["queryPlanner"]["winningPlan"]["stage"])
if "executionStats" in explain_after:
    print("Docs examined:", explain_after["executionStats"]["totalDocsExamined"])
    print("Execution ms:", explain_after["executionStats"]["executionTimeMillis"])
else:
    print("(executionStats not available)")

print("\nPerformance improvement: COLLSCAN -> IXSCAN, reduced examined documents.")

# MongoDB Analytical Insights

In [ ]:
# Insight 1: Hubs with most escalation flags
pipeline_hub_escalation = [
    {"$match": {"escalation_flag": "REVIEW_REQUIRED"}},
    {"$group": {
        "_id": "$delivery.hub_name",
        "count": {"$sum": 1},
        "avg_compensation": {"$avg": "$complaints.avg_compensation"},
        "avg_override_rate": {"$avg": "$delivery.overrides"},
        "sample_delay_categories": {"$push": "$risk_tags.delay_category"}
    }},
    {"$sort": {"count": -1}}
]

hub_escalation_results = list(collection.aggregate(pipeline_hub_escalation))

print("="*60)
print("Insight 1: Hubs with Most Escalation Flags (REVIEW_REQUIRED)")
print("="*60)
for r in hub_escalation_results:
    print(f"Hub: {r['_id']}")
    print(f"  Escalations: {r['count']}")
    print(f"  Avg Compensation: £{round(r.get('avg_compensation') or 0, 2)}")
    print(f"  Avg Override Rate: {round(r.get('avg_override_rate') or 0, 2)}")
    print(f"  Sample delay categories: {r['sample_delay_categories'][:3]}")
    print("-"*40)

In [ ]:
# Insight 2: App event latency by pickup zone
pipeline_latency_zone = [
    {"$match": {
        "app_events_summary.avg_api_latency_ms": {"$exists": True, "$ne": None}
    }},
    {"$group": {
        "_id": "$zone_context.pickup_zone",
        "avg_latency": {"$avg": "$app_events_summary.avg_api_latency_ms"},
        "max_latency": {"$max": "$app_events_summary.avg_api_latency_ms"},
        "orders": {"$sum": 1}
    }},
    {"$sort": {"avg_latency": -1}}
]

latency_results = list(collection.aggregate(pipeline_latency_zone))

print("="*60)
print("Insight 2: API Latency (ms) by Pickup Zone")
print("="*60)
for z in latency_results:
    print(f"Zone: {z['_id']}")
    print(f"  Avg latency: {round(z['avg_latency'], 1)} ms")
    print(f"  Max latency: {round(z['max_latency'], 1)} ms")
    print(f"  Orders with data: {z['orders']}")
    print("-"*40)

In [ ]:
# Insight 3: Cross‑tabulation of proof missing vs complaint flag
pipeline_proof_complaint = [
    {"$group": {
        "_id": {
            "proof_missing": "$delivery.proof_missing",
            "has_complaint": "$risk_tags.complaint_flag"
        },
        "count": {"$sum": 1},
        "avg_compensation": {"$avg": "$complaints.avg_compensation"},
        "total_compensation": {"$sum": "$complaints.avg_compensation"}
    }},
    {"$sort": {"_id.proof_missing": -1, "_id.has_complaint": -1}}
]

proof_complaint_results = list(collection.aggregate(pipeline_proof_complaint))

print("="*60)
print("Insight 3: Proof of Completion × Complaint Interaction")
print("="*60)
print(f"{'Proof Missing':<15} {'Has Complaint':<15} {'Count':<10} {'Avg Comp (£)':<15} {'Total Comp (£)'}")
print("-"*70)
for r in proof_complaint_results:
    proof = "Yes" if r['_id']['proof_missing'] else "No"
    complaint = "Yes" if r['_id']['has_complaint'] else "No"
    avg_comp = round(r.get('avg_compensation') or 0, 2)
    total_comp = round(r.get('total_compensation') or 0, 2)
    print(f"{proof:<15} {complaint:<15} {r['count']:<10} £{avg_comp:<14} £{total_comp}")

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Prepare data for bar chart
categories = []
counts = []
for r in proof_complaint_results:
    proof = "Missing" if r['_id']['proof_missing'] else "Has Proof"
    complaint = "+ Complaint" if r['_id']['has_complaint'] else "No Complaint"
    categories.append(f"{proof}\n{complaint}")
    counts.append(r['count'])

plt.figure(figsize=(8,5))
bars = plt.bar(categories, counts, color=['#d7301f' if 'Missing' in c else '#2c7bb6' for c in categories])
plt.title('Orders by Proof Status and Complaint Presence', fontsize=14)
plt.ylabel('Number of Orders')
plt.xlabel('Proof Status / Complaint')
for bar, count in zip(bars, counts):
    plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 5, str(count), ha='center', va='bottom')
plt.tight_layout()
plt.show()

#Final Markdown Summary Cell
# Notebook Summary

##This notebook reproduces all analyses from the NorthStar DBA report:
1. Data loading, cleaning, and master table creation (9 source files → orders_full_final.csv).
2. SQL within R: 9 queries producing the exact numbers (delay by zone, complaints, overrides, hub performance, driver risk, repeat customers, vehicle maintenance, monthly trend, CRUD demos).
3. R visualisations: 8 figures (boxplot, bar chart, heatmap, time series, correlation matrix, scatter, violin, bar).
4. Python feature engineering: delay categories, route risk score, customer risk segments, hub efficiency score, fleet health.
5. NumPy & Pandas analysis: zone summaries, hub ranking, customer segments, top routes, fleet health.
6. Pairwise plots and correlation heatmap.
7. MongoDB Atlas: embedded document design, CRUD, aggregation, indexing, explain plan optimisation.